### ISSUE TITLE
Support perl5.34 in lnxports

### ISSUE THREAD

**Issue by barracuda156** [RJVB/lnxports#10]
Currently perl5 has only perl5.30 as the highest version, but MacPorts uses 5.34 as the default.
perl5.34 from the standard portfile fails to install: https://trac.macports.org/ticket/70609
Could we add support for it in lnxports?

**Comment by RJVB** [comment]
This took me down a rabbithole...

See e9dd5678f91aee06ab3aefb2ac15953577f033c5 and 4f028f504bf96c9abc33680afb62bb838b286ecc

**Comment by barracuda156** [comment]
Thank you!
