### ISSUE TITLE
perl5.34: patches fail to apply

### ISSUE THREAD

**Issue by barracuda156** [RJVB/lnxports#11]
```
sh-5.1# port clean perl5.34
Warning: configured user/group macports does not exist, will build as root
--->  Cleaning perl5.34
sh-5.1# port -v install texinfo configure.compiler=clang
Warning: configured user/group macports does not exist, will build as root
--->  Computing dependencies for texinfo....
The following dependencies will be installed: 
 help2man
 p5.34-locale-gettext
 perl5.34
Continue? [Y/n]: y
Warning: configured user/group macports does not exist, will build as root
--->  Fetching distfiles for perl5.34
--->  Verifying checksums for perl5.34
--->  Checksumming perl-5.34.3.tar.xz
--->  Extracting perl5.34
--->  Extracting perl-5.34.3.tar.xz
--->  Applying patches to perl5.34
--->  Applying clean-up-paths.patch
patching file Configure
--->  Applying avoid-no-cpp-precomp-PR38913.patch
patching file hints/darwin.sh
--->  Applying fix-db_file-paths.patch
patching file cpan/DB_File/config.in
--->  Applying install-under-short-version-PR43480.patch
patching file Configure
--->  Applying patch-want-implicit-errors.diff
patching file cpan/ExtUtils-MakeMaker/lib/ExtUtils/MM_Darwin.pm
--->  Applying patch-always-provide-tsa_mutex-fncs.diff
patching file util.c
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file util.c.rej
Command failed:  cd "/opt/local/var/macports/build/_home_svacchanda_lnxports_lang_perl5/perl5.34/work/perl-5.34.3" && /usr/bin/patch -t -N -p0 < '/home/svacchanda/lnxports/lang/perl5/files/patch-always-provide-tsa_mutex-fncs.diff'
Exit code: 1
Error: Failed to patch perl5.34: command execution failed
Error: See /opt/local/var/macports/logs/_home_svacchanda_lnxports_lang_perl5/perl5.34/main.log for details.
```

**Comment by barracuda156** [comment]
@RJVB Thank you! I am still struggling with this failure, but it is an upstream one: https://github.com/Perl/perl5/issues/18467

Patches apply fine now :)

**Comment by RJVB** [comment]
Note that all my LinuxPorts ports will ask for perl 5.26 by default; does that one install OK?

**Comment by RJVB** [comment]
>Patches apply fine now :) 

Actually, they don't, not any finer than before. Failures in applying my last 2 patches are just being ignored ;)

**Comment by barracuda156** [comment]
> Note that all my LinuxPorts ports will ask for perl 5.26 by default; does that one install OK?

Let me try. 5.28 and 5.30 installed fine, 5.32 and 5.34 are broken.

BTW, how do I pass `-lintl` flag to miniperl linking? `configure.ldflags` is ignored, injecting the flag into configure args directly also has no effect.

**Comment by barracuda156** [comment]
UPD. Yeah, 5.26 installs fine.

**Comment by RJVB** [comment]
>BTW, how do I pass `-lintl` flag to miniperl linking? `configure.ldflags` is ignored, injecting the flag into configure args directly also has no effect.

Do you need to and for what Perl version(s)? I haven't run into this problem so have no idea. Setting the LDFLAGS variable in the build environment maybe?

**Comment by barracuda156** [comment]
> BTW, how do I pass `-lintl` flag to miniperl linking? `configure.ldflags` is ignored, injecting the flag into configure args directly also has no effect.
> Do you need to and for what Perl version(s)? I haven't run into this problem so have no idea. Setting the LDFLAGS variable in the build environment maybe?

5.32–5.34 fail, every earlier one builds fine.

5.26 as the default is problematic, because MacPorts dumped all subports for it in https://github.com/macports/macports-ports/commit/96a5edbb2a667d1908886915cbd016bfdbc0a42d

**Comment by RJVB** [comment]
>5.32–5.34 fail, every earlier one builds fine.

Because of -lintl? The presence of gettext can be problematic because most-but-not-all functions from libintl are usually provided by libc on LInux.  Building with the gettext headers but not linking libintl typically leads to link failures. This is why port:gettext was probably the first one for which I created the devport PG because I was fed up deactivating the entire port every time.

Try a fresh build of those failing versions after deactivating port:gettext-dev .

It's a bit strange though that gettext isn't listed as a dependency!

>5.26 as the default is problematic, because MacPorts dumped all subports for it

I'm aware, and I find it very annoying that the range of subports is defined with a list variable, but not in a PortGroup...

**Comment by barracuda156** [comment]
Is there a special reason to have it at 5.26 (well it seems really old)? Even 5.28 would be supported normally in standard MacPorts.

**Comment by RJVB** [comment]
On Wednesday September 04 2024 05:15:46 Sergey Fedorov wrote:
>Is there a special reason to have it at 5.26 (well it seems really old)? Even 5.28 would be supported normally in standard MacPorts.

Just the fact that I don't want to have to bother (re)installing all the p5 packages, and figuring out which ones I can uninstall safely if I don't want to also rebuild all dependents
