### ISSUE TITLE
perl5 wrapper port fails to install: `Error: Failed to destroot perl5: can't read "mandirsuffix": no such variable`

### ISSUE THREAD

**Issue by barracuda156** [RJVB/lnxports#13]
While I have built `perl5.26` with no issues, the wrapper fails to install:
```
Error: Failed to destroot perl5: can't read "mandirsuffix": no such variable
Error: See /opt/local/var/macports/logs/_home_svacchanda_lnxports_lang_perl5/perl5/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port perl5 failed
```

**Comment by barracuda156** [comment]
@RJVB Awesome, now this works and I can try building openssl3 and other stuff.

**Comment by barracuda156** [comment]
@RJVB Some port still want `perl5.34`:
```
sh-5.1# port -v install texinfo
Warning: configured user/group macports does not exist, will build as root
--->  Computing dependencies for texinfo....
The following dependencies will be installed: 
 help2man
 p5.34-locale-gettext
 perl5.34
```
How to force everything to use the same 5.26 without hacking every portfile?

**Comment by barracuda156** [comment]
Ah, `help2man` actually sets 5.34 in its portfile in MacPorts. Why on earth do they hardcode this...

**Comment by RJVB** [comment]
>Ah, `help2man` actually sets 5.34 in its portfile in MacPorts. Why on earth do they hardcode this...

Indeed. In the vast majority of cases one can simply depend on the wrapper ports (port:perl5 and port:p5-some-perl-module) ... And sadly I haven't found a way to avoid hacking every port that I need. Sometimes I just do that directly in the upstream tree that I'm using at that occasion.
