### ISSUE TITLE
Enable gcc13

### ISSUE THREAD

**Issue by barracuda156** [RJVB/lnxports#28]
It refuses to build now:
```
sh-5.1# port -v install gcc13 +no_sanit configure.compiler=clang
Warning: configured user/group macports does not exist, will build as root
WARNING: port:libiconv-dev not installed or not activated.
WARNING: port:gettext-dev not installed or not activated.
WARNING: port:libiconv-dev not installed or not activated.
WARNING: port:libiconv-dev not installed or not activated.
WARNING: port:gettext-dev not installed or not activated.
Error: Unable to open port: child process exited abnormally
Error: Unable to execute port gcc13: upgrade libgcc failed
sh-5.1# port -v -n install gcc13 +no_sanit configure.compiler=clang
Warning: configured user/group macports does not exist, will build as root
--->  Computing dependencies for gcc13.
--->  Fetching distfiles for gcc13
Error: this port has been disabled for now
Error: Failed to fetch gcc13: Port disabled.
Error: See /opt/local/var/macports/logs/_home_svacchanda_lnxports_lang_gcc13/gcc13/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port gcc13 failed
```

There are reasons to have at least gcc13 on riscv though, for example: https://github.com/google/highway/issues/2328
Also, runtime builds fine. Any reason to still prohibit gcc itself?

**Comment by RJVB** [comment]
On Saturday September 21 2024 07:00:53 Sergey Fedorov wrote:
>It refuses to build now:
...
>Error: this port has been disabled for now
>Error: Failed to fetch gcc13: Port disabled.

By design. GCC 12 is more than enough for me for now, and I just don't want to spend the time to port my changes to port:gcc13 and build it. I want to get out of my macports-hole for the most part and get on with other parts of my life for a while.

**Comment by barracuda156** [comment]
Will just copying Linux-specific stuff from gcc12 portfile to gcc13 work? (In principle at least, I am not asking for a guarantee.)

**Comment by RJVB** [comment]
The way I'd do it is use something like xxdiff to do a side-by-side comparison of the Portfiles to copy any mods from gcc12 to gcc13 and copy over any new patchfiles. Modified patchfiles are always trickier. Either way I'd use a comparison of the stock/mainstream gcc12 port with my own as a guideline.

**Comment by barracuda156** [comment]
Oh, awesome. I gave up on gcc12 since the error remained, and began porting changes from gcc12 to gcc13 portfile yesterday. Now I can just use the fixed version directly.

**Comment by RJVB** [comment]
Which error was that again?

I have hardly tested gcc13 but on Linux you don't need the libc++ support (I suppose) and any bootstrapped GCC build already had some rigorous testing via its compiling itself.
