### ISSUE TITLE
libiconv: allow for alternative locations of grep and sed

### ISSUE THREAD

**Issue by barracuda156** [RJVB/lnxports#3]
Both are hardcoded to /usr/bin: https://github.com/RJVB/lnxports/blob/a298f373201d7babb79337a6ff2ad53075c4ad7e/textproc/libiconv/Portfile#L65C1-L66C34

However, my Linux has them in /bin. In result, configure fails.

**Comment by RJVB** [comment]
>However, my Linux has them in /bin. In result, configure fails.

I think it should be OK to remove those 3 ac_cv_prog/path lines. I reckon they're there out of principle to avoid spurious dependencies on installed ports ... but I don't see how that could matter here.
